# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.srcs/sources_1/new/data_sync.v}
  C:/Users/Acer/Downloads/ELO212-example-modules-master/Lab5_UART_master_endpoint/Lab5_UART_master_endpoint.srcs/sources_1/new/TX_sequence.v
  {C:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.srcs/sources_1/new/tx_control_UART.v}
  {C:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.srcs/sources_1/new/to_ss.v}
  {C:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.srcs/sources_1/new/contador_bcd.v}
  {C:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.srcs/sources_1/new/uart_baud_tlk.v}
  {C:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.srcs/sources_1/new/uart_tx.v}
  {C:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.srcs/sources_1/new/uart_rx.v}
  C:/Users/Acer/Downloads/ELO212-example-modules-master/Lab5_UART_master_endpoint/Lab5_UART_master_endpoint.srcs/sources_1/new/UART_tx_control_wrapper.v
  {C:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.srcs/sources_1/new/double_dubble.v}
  {C:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.srcs/sources_1/new/clock_divider.v}
  {C:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.srcs/sources_1/new/alu.v}
  {C:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.srcs/sources_1/new/mux_ss.v}
  {C:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.srcs/sources_1/new/rx_control_UART.v}
  {C:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.srcs/sources_1/new/esclavo_endpoint.v}
  {C:/Users/Acer/Desktop/Laboratorio ELO212/esclavo_endpoint_uart/esclavo_endpoint_uart.srcs/sources_1/new/esclavo_endpoint_uart.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Acer/Desktop/Laboratorio ELO212/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Acer/Desktop/Laboratorio ELO212/Nexys4DDR_Master.xdc}}]


synth_design -top esclavo_endpoint_uart -part xc7a100tcsg324-1


write_checkpoint -force -noxdef esclavo_endpoint_uart.dcp

catch { report_utilization -file esclavo_endpoint_uart_utilization_synth.rpt -pb esclavo_endpoint_uart_utilization_synth.pb }
